---
# Title: dokuwiki
# Description: Dokuwiki installer based on linuxserver.io image
# Icon Url: https://raw.githubusercontent.com/mjh2901/docker_templates/master/dokuwiki_logo.png
version: "2.1"
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /docker/dokuwiki:/config
    ports:
      - 80:80
      - 443:443 #optional
    restart: unless-stopped